# Generated by Django 5.2.5 on 2025-09-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Ropa', 'Ropa'), ('Electrónica', 'Electrónica')], default='Ropa', max_length=20),
        ),
    ]
