"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Configuración de URLs para autenticación
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/' # Redirige al inicio después de cerrar sesión
AUTH_USER_MODEL = 'auth.User' # Usa el modelo de usuario por defecto

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3cfzaeqv8fn!siehb!(lno30d=bh8bgp3p+s$_@9#!mm(y@3j2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # Cambia esto por tu dominio en producción


# Application definition

INSTALLED_APPS = [
    # Core Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_app',
    'authentication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Busca plantillas en la carpeta 'templates' de la raíz del proyecto
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es' # Usando español
TIME_ZONE = 'UTC'

USE_I18N = True 
USE_TZ = True


# =================================================================
# 3. CONFIGURACIÓN DE ARCHIVOS ESTÁTICOS Y MULTIMEDIA (CORREGIDO)
# =================================================================

# URL base para servir archivos estáticos (CSS, JS)
STATIC_URL = '/static/'

# DIRECTORIO DE COLECCIÓN: Carpeta donde 'collectstatic' reunirá todo (para producción)
# Esto crea la carpeta 'static' en la raíz del proyecto.
STATIC_ROOT = BASE_DIR / 'static' 

# RUTA DE DESARROLLO: Directorios donde Django buscará archivos estáticos
# (si tienes CSS/JS globales fuera de la carpeta 'static' de tus apps)
# STATICFILES_DIRS = [
#     BASE_DIR / 'static_root_project',
# ]


# URL para servir archivos multimedia (imágenes de usuario)
# NOTA: Usamos '/media/' para desarrollo local. No debe ser '/static/...'.
MEDIA_URL = '/media/' 

# DIRECTORIO FÍSICO: La ubicación donde se guardan las imágenes.
# ANIDAMOS 'media' dentro de 'static' para simplificar el despliegue en PythonAnywhere.
MEDIA_ROOT = STATIC_ROOT / 'media' 

# =================================================================


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'